package com.socialapp.model;

import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDateTime;

/**
 * Represents a FriendRequest entity, mapping to the "friend_requests" collection in MongoDB.
 * <p>
 * This class defines the data structure for a sender, receiver, status of the request,
 * and the timestamp of when it was sent.
 */
@Document(collection = "friend_requests")
@Getter
@Setter
public class FriendRequest {

    /**
     * The unique identifier for the friend_requests document, automatically generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The unique identifier of the user who is sending the friend request.
     */
    private String senderId;

    /**
     * The unique identifier of the user who is receiving the friend request.
     */
    private String receiverId;

    /**
     * The indicator of the current status of the request.
     * It can take the values : {@code PENDING } , {@code ACCEPTED}, {@code REJECTED}
     */
    private Status status;

    /**
     * The timestamp indicating when the friend request was sent.
     * Defaults to the current time upon object creation.
     */
    private LocalDateTime createdAt =  LocalDateTime.now();

    /**
     * Default no-argument constructor.
     * Required by persistence frameworks like Spring Data for object instantiation.
     */
    public FriendRequest() {}

    /**
     * Represents the possible states of a friend request
     */
    public enum Status {
        /**
         * Initial State of the friend request
         */
        PENDING,

        /**
         * Success State of the friend request
         */
        ACCEPTED,

        /**
         * Failure State of the friend request
         */
        REJECTED
    }
}
